#config_version=5
# STAR WARS Attract Mode

###############################################################################################
#                                       PLAYERS                                               #
###############################################################################################


show_player:
  mode_attract_started: 
    attract_seg_show:
      speed: 1
      loops: -1

