#config_version=5
# STAR WARS

mode:
    start_events: 
        - droid_lock_enabled
    stop_events:
        - multiball_droid_mball_ended
        - multiball_starwars_mball_ended
       
    priority: 300

multiball_locks:
    droid:
        balls_to_lock: 1
        lock_devices: bd_droid
        locked_ball_counting_strategy: physical_only
        disable_events: multiball_droid_mball_started, multiball_ds_mball_started, multiball_starwars_mball_started

multiballs:
    droid_mball:
        ball_count: 1
        ball_count_type: add
        shoot_again: 10s
        ball_locks: bd_droid
        enable_events: multiball_lock_droid_locked_ball
        start_events: start_droid_multiball

light_player:

    multiball_lock_droid_locked_ball:
        l_droid_lock: on
    multiball_droid_mball_started:
        l_droid_lock: off


#############################################################
# SHOW PLAYER:  set lights on events
#############################################################

show_player:

    mode_droid_multiball_started: 
        show_flash:
            key: droid_flash
            show_tokens:
                led: l_droid_lock 
                color1: f5f5f5

    multiball_lock_droid_full:
        show_flash:
            key: droid_flash
            action: stop

    multiball_droid_mball_shoot_again:
        droid_ball_save:
            action: play

    multiball_droid_mball_shoot_again_ended:
        droid_ball_save:
            action: stop

#############################################################
# SHOWS
#############################################################

shows:
       
    droid_ball_save:
        - duration: .25
          lights:
              l_shootagain: f5f5f5
        - duration: .25
          lights:
              l_shootagain: off