#config_version=5
# STAR WARS

mode:
    start_events: 
        - droid_lock_enabled
        - ds_lock_enabled
    stop_events:
        - multiball_droid_mball_ended
        - multiball_deathstar_mball_ended
        - multiball_starwars_mball_ended
       
    priority: 400


#############################################################
# MULTIBALLS     yeah baby!!!
#############################################################

multiballs:
    starwars_mball:                 #### multiball when both deathstar and droid are locked
        ball_count: 2
        ball_count_type: add
        shoot_again: 10s
        ball_locks: bd_droid, bd_deathstar
        enable_events: multiball_lock_droid_locked_ball, multiball_lock_ds_locked_ball
        start_events: start_starwars_multiball

#############################################################
# LIGHT PLAYER:  set lights on events
#############################################################

light_player:

    multiball_starwars_mball_started:
        l_droid_lock: off
        l_spinner: off


#############################################################
# SHOW PLAYER:  set lights on events
#############################################################

show_player:

    multiball_starwars_mball_shoot_again:
        starwars_ball_save:
            action: play

    multiball_starwars_mball_shoot_again_ended:
        starwars_ball_save:
            action: stop

#############################################################
# SHOWS
#############################################################

shows:
       
    starwars_ball_save:
        - duration: .25
          lights:
              l_shootagain: f5f5f5
        - duration: .25
          lights:
              l_shootagain: off