#config_version=6
# STAR WARS 

###############################################################################################
#                                    WINDOW                                                   #
###############################################################################################


window:  # defines the area of the TV monitor that can be used for the backbox display
  title: SWbackbox
  width: 1080
  height: 1219    
  resizable: false
  fullscreen: false
  borderless: true
  exit_on_escape: true
  top: 0
  left: 0

###############################################################################################
#                                     DISPLAYS                                                #
###############################################################################################

displays:
  upperdisplay:
    width: 400
    height: 95
  lowerdisplay:
    width: 400
    height: 95
  bipdisplay:
    width: 50  
    height: 75
  backglass:
    width: 1080
    height: 1219
  window:
    width: 1080
    height: 1219

segment_displays:
  upperseg:
    default_transition_update_hz: 9
    size: 7
    number: 1
  lowerseg:
    default_transition_update_hz: 9
    size: 7
    number: 2
  bipseg:
    number: 3
    size: 1

virtual_segment_display_connector:
  segment_displays:
    - upperseg
    - lowerseg
    - bipseg

###############################################################################################
#                                       SLIDES                                                #
###############################################################################################

slides:
  layout: # THIS IS THE MAIN SLIDE THAT DRIVES ALL BACKBOX
    widgets: # these widgets are the...
      - type: display               # upper segment display
        width: 400
        height: 95
        x: 647
        y: 980
        anchor_x: left
        anchor_y: bottom
        source_display: upperdisplay

      - type: display               # lower segment display
        width: 400
        height: 95
        x: 647
        y: 800 
        anchor_x: left
        anchor_y: bottom
        source_display: lowerdisplay



      - type: display               # BIP segment display
        width: 50
        height: 75
        x: 965
        y: 224 
        anchor_x: left
        anchor_y: bottom
        source_display: bipdisplay

      - type: display               # background
        width: 1080
        height: 1219
        x: 0
        y: 0
        anchor_x: left
        anchor_y: bottom
        source_display: backglass
        
  background:
    widgets:
      - type: image
        image: sw_bg_unlit
        z: 5
  
  background_lit:
    widgets:
      - type: image
        image: sw_bg_lit
        z: 5

  uppersegment:
    widgets:
      - type: segment_display_emulator
        name: upperseg
        display_type: 8seg
        text: "       "
        character_count: 7
        character_slant_angle: 10
        character_spacing: 11
        padding: 12
        segment_width: 0.12
        segment_off_color: "012030"
        segment_on_color: 00acf0
        comma_enabled: true
        width: 400
        height: 95
        anchor_x: left
        anchor_y: bottom
        x: 0
        y: 0
        z: 10

  lowersegment:
    widgets:
      - type: segment_display_emulator
        name: lowerseg
        display_type: 8seg
        text: "       "
        character_count: 7
        character_slant_angle: 10
        character_spacing: 11
        padding: 12
        segment_width: 0.12
        segment_off_color: "012030"
        segment_on_color: 00acf0
        comma_enabled: true
        width: 400
        height: 95
        anchor_x: left
        anchor_y: bottom
        x: 0
        y: 0
        z: 10

  bipsegment:
    widgets:
      - type: segment_display_emulator
        name: bipseg
        display_type: 7seg
        text: " "
        character_count: 1
        character_slant_angle: 10
        character_spacing: 11
        padding: 12
        segment_width: 0.16
        segment_off_color: "012030"
        segment_on_color: 00acf0
        width: 50
        height: 75
        anchor_x: left
        anchor_y: bottom
        x: 0
        y: 0
        z: 10

