#config_version=5
# STAR WARS

#
keyboard:
  z:
    switch: s_left_flipper
  "/":
    switch: s_right_flipper
  "?":
    switch: s_right_flipper
  1:
    switch: s_trough_1
  s:
    switch: s_start

  9:
    switch: s_pop_1
  0:
    switch: s_pop_2

  d:
    switch: s_dingwalls
  x:
    switch: s_l_outlane
  v:
    switch: s_l_inlane
  b:
    switch: s_r_inlane
  n:
    switch: s_r_outlane
  m:
    switch: s_left_sling 
  t:
    switch: s_tilt_bob
#