#config_version=6
# STAR WARS

mode:
    start_events: 
        - right_inlane_hit
    stop_events:
        - timer_spinner_timer_complete
    priority: 300

#############################################################
# TIMERS            to control spinner scoring
#############################################################

timers:

    spinner_timer:
        direction: down
        start_value: 4
        end_value: 0
        max_value: 4
        tick_interval: 1s
        control_events:
            - event: right_inlane_hit
              action: restart
            - event: spinner_left_spinner_hit
              action: add
              value: 2
            - event: mode_spinnertimer_started
              action: start
 

#############################################################
# SHOW PLAYER:  
#############################################################

show_player:
    mode_spinnertimer_started: spinner_attract


#############################################################
# SHOWS
#############################################################

shows:
    spinner_attract:

    - duration: .2
      lights:
          l_spinner: off
          l_escape_1: f5f5f5
    - duration: .2
      lights:
          l_escape_1: off
          l_escape_2: f5f5f5
    - duration: .2
      lights:
          l_escape_2: off
          l_escape_3: f5f5f5
    - duration: .2
      lights:
          l_escape_3: off
          l_spinner: f5f5f5

