#config_version=5
# STAR WARS

mode:
    start_events: 
        - multiball_starwars_mball_started
    stop_events: 
        - extra_ball_awarded
        - multiball_starwars_mball_ended
    priority: 500


shots:
    extra_ball:
        switch: s_ds_target


extra_balls:
    deathstar_extra_ball:
        award_events: extra_ball_hit
        group: main
